version: "3.3"

services:

  spark-master-demo:
    build: ./docker   
    container_name: spark-master-demo
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - bigdataprj_my-net
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"
    
  spark-worker-demo:
    build: ./docker 
    depends_on:
      - spark-master-demo
    ports:
      - 8080
    networks:
      - bigdataprj_my-net
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"

  spark-driver:
    build: ./docker
    image: spark-driver
    ports:
      - 8888:8888
    depends_on:
      - spark-master-demo
      - spark-worker-demo
    networks:
      - bigdataprj_my-net
    volumes:
      - "./:/project"
      
networks:
  bigdataprj_my-net:
    external: true
    # driver: bridge
    # ipam:
    #   driver: default