### 1. Get Linux
FROM alpine:3.9

### 2. Get Java via the package manager
RUN apk update \
&& apk upgrade \
&& apk add --no-cache bash \
&& apk add --no-cache --virtual=build-dependencies unzip \
&& apk add --no-cache curl \
&& apk add --no-cache openjdk8-jre


### 3. Get Python, PIP
RUN apk add --no-cache python3 \
&& python3 -m ensurepip \
&& pip3 install --upgrade pip setuptools \
&& rm -r /usr/lib/python*/ensurepip && \
if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
rm -r /root/.cache

### 4. get Jupyter Notebook
RUN apk add libffi-dev gcc python3-dev libc-dev
RUN pip install notebook tqdm

### 5. get Spark
RUN apk --update add wget tar bash \
&& wget https://archive.apache.org/dist/spark/spark-3.3.1/spark-3.3.1-bin-hadoop2.tgz \
&& tar -xvf spark-3.3.1-bin-hadoop2.tgz \
&& mv spark-3.3.1-bin-hadoop2 /spark \
&& rm spark-3.3.1-bin-hadoop2.tgz

COPY start-master.sh /start-master.sh
COPY start-worker.sh /start-worker.sh